ccflags-y := -I$(obj)/../../exports -I$(obj)/..
ccflags-y += -DNSS_PPE_BUILD_ID="$(BUILD_ID)"

obj-m += qca-nss-ppe-dsa-mgr.o
qca-nss-ppe-dsa-mgr-objs := nss_ppe_dsa_mgr.o

ccflags-y += -DNSS_PPE_DSA_MGR_DEBUG_LEVEL=3
ccflags-y += -Wall -Werror

ifeq ($(SoC),$(filter $(SoC),ipq53xx ipq54xx ipq96xx ipq52xx))
ccflags-y += -DNSS_ATH_HDR_BASED_DSA_SUPPORT
endif